= SuperGenPass context menu for Firefox

https://chriszarate.github.io/supergenpass/[SuperGenPass] is a useful hash-based password generator, creating unique password based on your master password and site's domain.

The bookmarklet is quite evolved and stable, there are however sites that prevent executing bookmarklets by means of content security policies (like GitHub). 
Then it is very practical to have the functionality in the browser.

== Features

Currently the features are barebone - in any password field enter your master password, enter the context menu (i. e. right click or Shift+F10 on Windows).
The password will ge generated with SGP default settings (SuperGenPass MD5, 10 rounds, subdomain eliminiation).
Currently there is no way to change these, as this was my short visit to Add-On APIs and javascript development in general

== Acknowledgements

The plugin uses https://github.com/chriszarate/supergenpass/blob/607c4dcc26d7396cf0585aaf5aa07eb506a32064/js/sgp.js[code of SuperGenPass 2.0] by https://github.com/chriszarate[@chriszarate].

I did not base the code on more recent versions, as they pull in lots of dependencies and need special treatment to work in browsers, while I only needed those 200 lines.
